version: "3"

services:
  db:
    container_name: monguito
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: adopciones
  
  app:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: python adoption_ms/manage.py runserver 0.0.0.0:3000
    links:
      - db
     