version: "3"

services:
  app:
    container_name: djangoBackAdoption
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: python adoption_ms/manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/app

networks:
  default:
    external:
      name: $NETWORK