# Generated by Django 4.1.13 on 2024-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=255)),
                ('campo2', models.IntegerField()),
                ('campo3', models.IntegerField()),
            ],
        ),
    ]
